### PR TITLE
Update and fix examples

### PR DESCRIPTION
**Pull request by loganmac**
I was just playing around with the alpha and needed an example of using this. When I came across the examples, they got me almost there, but I had to finish them like this PR does to get them to run in Ellie. I thought I'd contribute these back so that the next person looking for examples doesn't have to do this.

Here are some Ellies pointing to the working examples:

drag: https://ellie-test-19-cutover.now.sh/33pKWyW8mGJa1
wasd: https://ellie-test-19-cutover.now.sh/33pQTVhM7jga1

Note: In the drag example, I added the wrapping div to prevent a bug where you could accidentally mouseup outside the element and lose track of it.

### CODE REVIEW

**Comment by evancz** [comment]
Can you do a PR that only has the code changes? The reformat makes it really hard to tell what you had to change.

**Comment by loganmac** [comment]
Sure, I can! @evancz, for my own information, is elm-format not the community standard when contributing?

**Comment by evancz** [comment]
It is the standard. The code here is sort of a draft, so it's just harder to review a PR if it does two things at once.

**Comment by loganmac** [comment]
Okay, I totally understand. Thank you!

**Pull request closed without merging**
