### PR TITLE
Fix and update examples (no format change)

### PR DESCRIPTION
**Pull request by loganmac**
Reopen of #14 that removes formatting changes

### CODE REVIEW

**Comment by Rolograaf** [comment]
Thank you, please merge? took me some time to find this

**Comment by nickcanz** [comment]
Just chiming in to say that this PR is still relevant, the examples as they exist don't work currently. The fixes in this PR *do* work.

**Comment by DestyNova** [comment]
Is there a good reason not to merge this? The current example is outdated and does not work, so this is really helpful.

**Comment by evancz** [comment]
The code in examples/ was part of my explorations while designing this library.

I just redid the drag example to cover a case I need in practice from time to time: having two panels that you can resize by dragging the border between them. It now lives in https://github.com/elm/browser/tree/master/examples in place of the exploratory files.

Sorry for the confusion on this!

**Pull request closed without merging**
